name: 'Set up tox'
description: 'Set up tox'
inputs:
  python-version:
    description: 'The Python version to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.python-version }}
        cache: pip

    - name: Install tox
      shell: bash
      run: python -m pip install -r pretest-requirements.txt
